(package "company-fuzzy"
         "1.4.0"
         "Fuzzy matching for `company-mode'")

(website-url "https://github.com/jcs-elpa/company-fuzzy")
(keywords "auto" "auto-complete" "complete" "fuzzy" "matching")

(package-file "company-fuzzy.el")

(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "company")
(depends-on "s")
(depends-on "ht")

(development
 (depends-on "ert-runner"))

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
